### ISSUE TITLE
feat:  make a bigger button for our matrix space

### ISSUE THREAD

**Issue by cafkafk** [eza-community/eza#331]
Having people on matrix so far has been invaluable. I feel like the current badge probably is missed by most people.

I'd like to add some larger "thing" to the readme, both here and https://github.com/eza-community/.github/

Link to matrix space: https://matrix.to/#/#eza-community:gitter.im

# Todo

- [x] Figure out what to add
- [x] Add it to eza
- [ ] Add it to org

**Comment by MartinFillon** [comment]
Can you push the same changes to the .github repo ? @cafkafk as you are one of the maintainers

**Comment by cafkafk** [comment]
> Can you push the same changes to the .github repo ? @cafkafk as you are one of the maintainers

done and done, thanks for your help
