### ISSUE TITLE
All the exa issues

### ISSUE THREAD

**Issue by sbatial** [eza-community/eza#65]
- [x] ogham/exa/pull/1221 > #2 
- [x] ogham/exa/pull/1219 > #3 
- [x] ~ogham/exa/pull/1210~ > #4 
- [ ] ogham/exa/pull/1204 > #5 
- [x] ~ogham/exa/pull/1202~ > #6 
- [x] ~ogham/exa/pull/1201~ > #7 
- [x] ogham/exa/pull/1199 > #8 
- [ ] ogham/exa/pull/1196 > #9 
- [x] ogham/exa/pull/1194 > #10 
- [x] ~ogham/exa/pull/1192~ > #11 
- [x] ogham/exa/pull/1191 > #12 
- [ ] ogham/exa/pull/1190 > #13 
- [x] ogham/exa/pull/1188 > #14 
- [ ] ogham/exa/pull/1184 > #15
- [x] ogham/exa/pull/1178 > #16 
- [x] ogham/exa/pull/1177 > #17 
- [x] ogham/exa/pull/1175 > #18 
- [ ] ogham/exa/pull/1169 > #19 
- [ ] ogham/exa/pull/1165 > #20 
- [x] ogham/exa/pull/1164 > #21 
- [x] ogham/exa/pull/1162 > #22 
- [x] ogham/exa/pull/1160 > #23 
- [ ] ogham/exa/pull/1156 > #24 
- [x] ogham/exa/pull/1150 > #25 
- [ ] ogham/exa/pull/1149 > #26 
- [x] ogham/exa/pull/1148 > #27 
- [ ] ogham/exa/pull/1146 > #28 
- [x] ~ogham/exa/pull/1144~ > #29 
- [ ] ogham/exa/pull/1141 > #30 
- [x] ogham/exa/pull/1140 > #31 
- [ ] ogham/exa/pull/1136 > #32 
- [x] ogham/exa/pull/1128 > #33 
- [x] ogham/exa/pull/1121 > #34 
- [x] ogham/exa/pull/1120 > #35 
- [ ] ogham/exa/pull/1119 > #36 
- [ ] ogham/exa/pull/1102 > #37 
- [ ] ogham/exa/pull/1100 > #38 
- [x] ogham/exa/pull/1099 > #39 
- [x] ogham/exa/pull/1094 > #40 
- [x] ogham/exa/pull/1085 > #41 
- [ ] ogham/exa/pull/1070 > #42 
- [x] ogham/exa/pull/1064 > #43 
- [x] ogham/exa/pull/1061 > #44 
- [x] ogham/exa/pull/1057 > #45 
- [x] ogham/exa/pull/1051 > #46 
- [x] ~ogham/exa/pull/1049~ > #47 
- [ ] ogham/exa/pull/1018 > #48 
- [x] ogham/exa/pull/1006 > #49 
- [x] ogham/exa/pull/981 > #50 
- [ ] ogham/exa/pull/975 > #51 
- [ ] ogham/exa/pull/960 > #52 
- [ ] ogham/exa/pull/941 > #53 
- [ ] ogham/exa/pull/908 > #54 
- [x] ~ogham/exa/pull/880~ > #55 
- [ ] ogham/exa/pull/872 > #56 
- [ ] ogham/exa/pull/869 > #57 
- [ ] ogham/exa/pull/867 > #58 
- [x] ~ogham/exa/pull/861~ > #59 
- [ ] ogham/exa/pull/857 > #60 
- [x] ogham/exa/pull/855 > #61 
- [x] ogham/exa/pull/797 > #62 
- [ ] ogham/exa/pull/786 > #63 
- [x] ogham/exa/pull/370 > #64

**Comment by sbatial** [comment]
Close it if you don't think it's useful.
But it's the simplest way to track what is merged from exa I guess.

I hope you can edit as well to tick off boxes

**Comment by cafkafk** [comment]
I don't think this is as useful anymore, as most of the PR's that are left over are essentially stale. Will close for now.

**Comment by daviessm** [comment]
I know it's closed but for reference can you update ogham/exa#941 to be #167

**Comment by cafkafk** [comment]
> I know it's closed but for reference can you update [ogham/exa#941](https://github.com/ogham/exa/pull/941) to be #167

yup, done :+1:
